[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "voxelator"
version="1.0.0"
dependencies = [
    "jsonargparse", "rich",
    "numpy==1.26", "matplotlib", "pillow",
    "scikit-image", "trimesh", "manifold3d", "pyrender"
] # project  dependencies

[project.optional-dependencies]
full = ["trimesh[easy]", "open3d"]

[project.scripts]
gyroid="tutorial.gyroid:create_gyroid_cli"
qrcode="tutorial.qrcode:qrcode_cli"
voxelize="tutorial.voxelize:voxelize_cli"
arr2stl="voxelator.arr2stl:arr2stl_cli"

[tool.setuptools]
packages = ["voxelator", "tutorial"]